version: 0.0
os: linux

files:
  # Specifies which files from S3 should be transferred to the destination (EC2).
  # Using / means all files in the S3 bundle will be transferred.
  - source: /
    # Specifies the destination path on the EC2 instance.
    destination: /home/ubuntu/linond-server

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: ubuntu
